import { format } from "date-fns";
import { Activity, Rocket, Sparkles, Target } from "lucide-react";
import Link from "next/link";

import { prisma } from "@/lib/db";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

function StatCard({ label, value, description, icon: Icon }: { label: string; value: string; description: string; icon: any }) {
  return (
    <Card className="border-white/10 bg-white/5 text-slate-100 shadow-[0_10px_50px_rgba(15,23,42,0.35)] backdrop-blur">
      <CardHeader className="flex flex-row items-center justify-between gap-4">
        <div>
          <p className="text-xs uppercase tracking-[0.32em] text-slate-400">{label}</p>
          <CardTitle className="text-3xl font-semibold text-white">{value}</CardTitle>
        </div>
        <div className="rounded-full border border-white/20 bg-white/10 p-3 text-white">
          <Icon className="h-5 w-5" />
        </div>
      </CardHeader>
      <CardContent>
        <p className="text-sm text-slate-300">{description}</p>
      </CardContent>
    </Card>
  );
}

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function DashboardOverviewPage() {
  const [productsCount, ordersCount, scriptsCount, campaignsCount, latestOrders, campaigns] = await Promise.all([
    prisma.product.count(),
    prisma.order.count(),
    prisma.script.count(),
    prisma.campaign.count(),
    prisma.order.findMany({ include: { product: true }, orderBy: { createdAt: "desc" }, take: 3 }),
    prisma.campaign.findMany({ orderBy: { startsOn: "asc" }, take: 4 }),
  ]);

  return (
    <div className="space-y-10">
      <header className="flex flex-col gap-6 rounded-3xl border border-white/10 bg-gradient-to-br from-white/10 via-white/5 to-transparent p-8 text-white">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
          <div className="space-y-2">
            <Badge variant="outline" className="border-white/50 bg-white/10 text-white">
              Live Sandbox
            </Badge>
            <h2 className="text-3xl font-semibold tracking-tight text-white">Welcome back, Operator</h2>
            <p className="max-w-2xl text-sm text-slate-200">
              Review performance, ship new scripts, and track every DM-to-checkout journey without leaving your offline lab.
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button
              asChild
              className="rounded-full border border-orange-300/40 bg-orange-500 text-white hover:bg-orange-400"
            >
              <Link href="/dashboard/dm-studio">Launch DM Studio</Link>
            </Button>
            <Button
              asChild
              variant="outline"
              className="rounded-full border-orange-300/60 bg-orange-500/10 text-orange-100 hover:bg-orange-500/20 hover:text-white"
            >
              <Link href="/dashboard/products">Create product</Link>
            </Button>
          </div>
        </div>
      </header>

      <section className="grid gap-6 lg:grid-cols-4">
        <StatCard
          label="Products"
          value={productsCount.toString()}
          description="Live offers ready for DM handoff"
          icon={Sparkles}
        />
        <StatCard
          label="Orders"
          value={ordersCount.toString()}
          description="Completed DM-to-checkout conversions"
          icon={Activity}
        />
        <StatCard
          label="Scripts"
          value={scriptsCount.toString()}
          description="Reusable flows in your library"
          icon={Target}
        />
        <StatCard
          label="Campaigns"
          value={campaignsCount.toString()}
          description="Keyword-triggered campaigns ready to run"
          icon={Rocket}
        />
      </section>

      <section className="grid gap-6 lg:grid-cols-2">
        <Card className="border-white/10 bg-white/5 text-white">
          <CardHeader>
            <CardTitle className="text-xl">Latest conversions</CardTitle>
            <p className="text-sm text-slate-300">Recent fake checkouts generated by DM flows.</p>
          </CardHeader>
          <CardContent className="space-y-5">
            {latestOrders.length === 0 ? (
              <div className="rounded-2xl border border-dashed border-white/20 p-6 text-center text-slate-300">
                No orders yet. Run the checkout demo from Products to see fulfillment in action.
              </div>
            ) : (
              <div className="space-y-4">
                {latestOrders.map((order) => (
                  <div key={order.id} className="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 p-4">
                    <div>
                      <p className="text-sm font-medium text-white">{order.product.title}</p>
                      <p className="text-xs text-slate-300">{order.buyerEmail}</p>
                    </div>
                    <div className="text-right text-xs text-slate-300">
                      <p>{format(new Date(order.createdAt), "PP")}</p>
                      <p className="font-mono text-sm text-white">${(order.product.priceCents / 100).toFixed(2)}</p>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
        <Card className="border-white/10 bg-white/5 text-white">
          <CardHeader>
            <CardTitle className="text-xl">Active campaigns</CardTitle>
            <p className="text-sm text-slate-300">Monitor keywords, scripts, and their next send.</p>
          </CardHeader>
          <CardContent className="space-y-4">
            {campaigns.length === 0 ? (
              <div className="rounded-2xl border border-dashed border-white/20 p-6 text-center text-slate-300">
                No campaigns scheduled. Create one from the Campaigns view to simulate DM triggers.
              </div>
            ) : (
              <div className="space-y-3">
                {campaigns.slice(0, 4).map((campaign) => {
                  const now = new Date();
                  const start = new Date(campaign.startsOn);
                  const end = new Date(campaign.endsOn);
                  const status = now < start ? "Scheduled" : now > end ? "Completed" : "Active";

                  return (
                    <div key={campaign.id} className="rounded-2xl border border-white/10 bg-white/5 p-4">
                      <div className="flex items-center justify-between text-sm">
                        <span className="font-semibold text-white">{campaign.name}</span>
                        <Badge variant="secondary" className="rounded-full bg-white/20 text-white">
                          {status}
                        </Badge>
                      </div>
                      <div className="mt-2 grid gap-1 text-xs text-slate-300">
                        <span>Keyword: <strong>{campaign.keyword}</strong></span>
                        <span>
                          Timeline: {format(start, "MMM d")} - {format(end, "MMM d")}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
      </section>

      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 text-white">
        <h3 className="text-lg font-semibold">Quick start checklist</h3>
        <ul className="mt-4 grid gap-3 text-sm text-slate-200 lg:grid-cols-2">
          {["Create or import a DM script", "Launch the DM Studio simulator", "Send a fake checkout to confirm delivery", "Customize brand palette in Settings"].map((item) => (
            <li key={item} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/20 text-xs font-semibold">✓</span>
              {item}
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
